Current gcc requires cstdint for C types
Add #include <cstdint> to resolve the issues similar to the following:

  module/module_structs.h:259:3: note: 'uint16_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  module/module_structs.h:260:3: error: 'uint16_t' does not name a type

Signed-off-by: Mark Hatle <mark.hatle@amd.com>
Acked-by: Varunkumar Allagadapa <varunkumar.allagadapa@amd.com>